namespace LoopGame.Application.Dtos.SideTaskDtos;

/// <summary>
/// A single side task generated by the external AI service.
/// </summary>
public class AiGeneratedTaskDto
{
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string FilledSlotsJson { get; set; } = "{}";
    
    /// <summary>
    /// Difficulty score provided by AI (lower = easier, used for sorting tasks easiest -> hardest).
    /// </summary>
    public int Difficulty { get; set; }
    
    public decimal EgpReward { get; set; }
    public List<AiGeneratedTestCaseDto> TestCases { get; set; } = [];
}

public class AiGeneratedTestCaseDto
{
    public string TestInput { get; set; } = string.Empty;
    public string ExpectedOutput { get; set; } = string.Empty;
    public bool IsHidden { get; set; } = false;
    public string? Description { get; set; }
}
