using LoopGame.Domain.Enums;

namespace LoopGame.Application.Dtos.SideTaskDtos;

/// <summary>
/// A single side task generated by the external AI service.
/// </summary>
public class AiGeneratedTaskDto
{
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string FilledSlotsJson { get; set; } = "{}";

    /// <summary>
    /// Difficulty score provided by AI (lower = easier, used for sorting tasks easiest -> hardest).
    /// </summary>
    public int Difficulty { get; set; }

    public decimal EgpReward { get; set; }
    public List<AiGeneratedTestCaseDto> TestCases { get; set; } = [];

    /// <summary>
    /// Progressive hints generated by the AI (up to 3 levels).
    /// Saved as SideTaskHint rows linked to the PlayerSideTask.
    /// </summary>
    public List<AiGeneratedHintDto> Hints { get; set; } = [];
}

public class AiGeneratedTestCaseDto
{
    public string TestInput { get; set; } = string.Empty;
    public string ExpectedOutput { get; set; } = string.Empty;
    public bool IsHidden { get; set; } = false;
    public string? Description { get; set; }
}

/// <summary>
/// A single AI-generated hint, matching the SideTaskHint entity.
/// HintLevel maps to: 1 = ConceptualNudge, 2 = StructuralGuidance, 3 = CodeSnippet.
/// </summary>
public class AiGeneratedHintDto
{
    /// <summary>1 = Conceptual Nudge, 2 = Structural Guidance, 3 = Code Snippet.</summary>
    public int HintLevel { get; set; }

    public string HintText { get; set; } = string.Empty;

    /// <summary>EGP cost the player pays to unlock this hint (default 0).</summary>
    public decimal EgpCost { get; set; } = 0m;
}
