// <auto-generated />
using System;
using LoopGame.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoopGame.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825120346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoopGame.Domain.Entities.Assessment.AssessmentEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<string>("ConceptTag")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("varchar(20)");

                    b.HasKey("EventId");

                    b.HasIndex("PlayerId", "EventType", "RecordedAt")
                        .HasDatabaseName("IX_Assessment_Player_Type");

                    b.ToTable("AssessmentEvent", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Assessment_EventType", "\"EventType\" IN ('choice_submission','practice_attempt','hint_request','side_task_submission','desktop_interaction','consequence_trigger','gate_cleared','shift_completed')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Assessment.ConceptMasterySnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("ConceptTag")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EvidenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("MasteryScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshottedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("SnapshotId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ConceptMasterySnapshot", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Mastery_Score", "\"MasteryScore\" BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Audit.AiGenerationLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() + INTERVAL '2 years'");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParsedSlots")
                        .HasColumnType("jsonb");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("LogId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_AiLog_Expiry");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("AiGenerationLog", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuditId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Code.PracticeAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptId"));

                    b.Property<bool>("HintUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SubmittedCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<string>("TestResults")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TimeSpentSec")
                        .HasColumnType("integer");

                    b.HasKey("AttemptId");

                    b.HasIndex("TaskId");

                    b.HasIndex("PlayerId", "TaskId", "SubmittedAt")
                        .HasDatabaseName("IX_Attempt_Player_Task");

                    b.ToTable("PracticeAttempt", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_PracticeAttempt_Tier", "\"Tier\" IN ('Ideal', 'Acceptable', 'Debt', 'Mistake')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Code.PracticeTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<string>("ConceptTag")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Standard");

                    b.Property<decimal>("EgpReward")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<short>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("StarterCode")
                        .HasColumnType("text");

                    b.Property<byte>("TaskOrder")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TaskId");

                    b.HasIndex("ShiftId");

                    b.ToTable("PracticeTask", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_PracticeTask_Difficulty", "\"Difficulty\" IN ('SpacedRetrieval', 'Standard', 'Challenge')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Code.TestCase", b =>
                {
                    b.Property<int>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestCaseId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int?>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("TestInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestCaseId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TestCase", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_TestCase_Parent", "(\"TaskId\" IS NOT NULL AND \"TemplateId\" IS NULL) OR (\"TaskId\" IS NULL AND \"TemplateId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.PlayerEconomy", b =>
                {
                    b.Property<int>("EconomyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EconomyId"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SalaryTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TotalEarned")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("EconomyId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerEconomy", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Economy_Balance", "\"Balance\" >= 0");

                            t.HasCheckConstraint("CHK_Economy_SalaryTier", "\"SalaryTier\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.PlayerInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<decimal>("EgpPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("InventoryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlayerInventory");

                    b.ToTable("PlayerInventory", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.SahmSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<DateTime>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte>("DailyHintLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)3);

                    b.Property<byte>("HintsUsedToday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateOnly>("LastHintReset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Free");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("SahmSubscription", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Sahm_Tier", "\"Tier\" IN ('Free','Pro','Team','Enterprise')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.ShopItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("AssetKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOneWay")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RankRequired")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemKey")
                        .IsUnique();

                    b.ToTable("ShopItem", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_ShopItem_Category", "\"Category\" IN ('sahm_tier','camera','desk_item','workspace')");

                            t.HasCheckConstraint("CHK_ShopItem_Price", "\"Price\" > 0");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("transaction_type");

                    b.HasKey("TransactionId");

                    b.HasIndex("PlayerId", "CreatedAt")
                        .HasDatabaseName("IX_Transaction_Player_Date");

                    b.ToTable("Transaction", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Transaction_Type", "transaction_type IN ('salary','bonus','side_task','purchase','penalty','bug_bounty')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("character(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshToken_User_Expiry")
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("RefreshToken", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChoiceId"));

                    b.Property<int>("BeatId")
                        .HasColumnType("integer");

                    b.Property<byte>("ChoiceIndex")
                        .HasColumnType("smallint");

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ConsequenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ImmediateFeedback")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("ChoiceId");

                    b.HasIndex("ConsequenceId");

                    b.HasIndex("BeatId", "ChoiceIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_Choice_Beat_Index");

                    b.ToTable("Choice", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Choice_Index", "\"ChoiceIndex\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.Consequence", b =>
                {
                    b.Property<int>("ConsequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConsequenceId"));

                    b.Property<int>("BeatId")
                        .HasColumnType("integer");

                    b.Property<string>("InjectPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("start");

                    b.HasKey("ConsequenceId");

                    b.HasIndex("BeatId")
                        .IsUnique()
                        .HasDatabaseName("IX_Consequence_Beat");

                    b.ToTable("Consequence", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Consequence_InjectPosition", "\"InjectPosition\" IN ('start', 'end')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCapstone")
                        .HasColumnType("boolean");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UnlockCondition")
                        .HasColumnType("jsonb")
                        .HasColumnName("unlock_condition");

                    b.HasKey("ShiftId");

                    b.HasIndex("ChapterNumber", "ShiftNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Shift_Number");

                    b.ToTable("Shift", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.StoryBeat", b =>
                {
                    b.Property<int>("BeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BeatId"));

                    b.Property<string>("App")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("app");

                    b.Property<string>("BeatKey")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BeatType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("narrative")
                        .HasColumnName("beat_type");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("DelaySeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,1)")
                        .HasDefaultValue(0m);

                    b.Property<string>("DesktopEvent")
                        .HasColumnType("jsonb")
                        .HasColumnName("desktop_event");

                    b.Property<bool>("HasChoices")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.HasKey("BeatId");

                    b.HasIndex("BeatKey")
                        .IsUnique();

                    b.HasIndex("ShiftId", "BeatType", "SequenceOrder")
                        .HasDatabaseName("IX_Beat_Shift_Seq");

                    b.ToTable("StoryBeat", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Beat_SequenceOrder", "(beat_type = 'narrative' AND \"SequenceOrder\" IS NOT NULL) OR (beat_type = 'consequence' AND \"SequenceOrder\" IS NULL)");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.ConsequenceQueue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QueueId"));

                    b.Property<int>("ConsequenceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("QueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending");

                    b.HasKey("QueueId");

                    b.HasIndex("ConsequenceId");

                    b.HasIndex("PlayerId", "ConsequenceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Queue_Player_Consequence");

                    b.HasIndex("PlayerId", "Status")
                        .HasDatabaseName("IX_Queue_Player_Status");

                    b.ToTable("ConsequenceQueue", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_Queue_Status", "\"Status\" IN ('pending', 'fired', 'dismissed')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CurrentShiftId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Intern");

                    b.Property<string>("StudentIdHash")
                        .IsRequired()
                        .HasColumnType("character(64)");

                    b.Property<int>("TotalPlayTimeSec")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("CurrentShiftId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Player_User");

                    b.HasIndex("StudentIdHash")
                        .IsUnique();

                    b.ToTable("Player", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.PlayerChoice", b =>
                {
                    b.Property<int>("PlayerChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerChoiceId"));

                    b.Property<int>("BeatId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChosenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionContext")
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("PlayerChoiceId");

                    b.HasIndex("BeatId");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("PlayerId", "BeatId")
                        .HasDatabaseName("IX_Choice_Player_Beat");

                    b.ToTable("PlayerChoice", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.PlayerSave", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaveId"));

                    b.Property<string>("DesktopState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("desktop_state");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SaveLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte>("SlotNumber")
                        .HasColumnType("smallint");

                    b.HasKey("SaveId");

                    b.HasIndex("PlayerId", "SlotNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlayerSave");

                    b.ToTable("PlayerSave", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_PlayerSave_SlotNumber", "\"SlotNumber\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.PlayerShiftProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("GateAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("in_progress");

                    b.HasKey("ProgressId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("PlayerId", "ShiftId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlayerShift");

                    b.ToTable("PlayerShiftProgress", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_ShiftProgress_Status", "\"Status\" IN ('in_progress', 'gate_pending', 'completed')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.PlayerSideTask", b =>
                {
                    b.Property<int>("SideTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SideTaskId"));

                    b.Property<int?>("AiLogId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EgpReward")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("FilledSlots")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolvedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolvedTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("SideTaskId");

                    b.HasIndex("AiLogId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PlayerSideTask", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_PlayerSideTask_Status", "\"Status\" IN ('active', 'submitted', 'abandoned', 'expired')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.SideTaskHint", b =>
                {
                    b.Property<int>("HintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HintId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("EgpCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<short>("HintLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("HintText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("SideTaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HintId");

                    b.HasIndex("SideTaskId", "HintLevel")
                        .IsUnique()
                        .HasDatabaseName("IX_SideTaskHint_Task_Level");

                    b.ToTable("SideTaskHint", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_SideTaskHint_Level", "\"HintLevel\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.SideTaskSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionId"));

                    b.Property<decimal>("EgpEarned")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("SahmHintsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("SideTaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SubmittedCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestResults")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TimeSpentSec")
                        .HasColumnType("integer");

                    b.HasKey("SubmissionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SideTaskId");

                    b.ToTable("SideTaskSubmission", "public", t =>
                        {
                            t.HasCheckConstraint("CHK_SideTaskSubmission_Tier", "\"Tier\" IN ('Ideal', 'Acceptable', 'Debt', 'Mistake')");
                        });
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.SideTaskTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("ConceptTag")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DescriptionTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EgpMax")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(3000m);

                    b.Property<decimal>("EgpMin")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(500m);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RankRequired")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Intern");

                    b.Property<string>("SlotsSchema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateKey")
                        .IsUnique();

                    b.ToTable("SideTaskTemplate", "public");
                });

            modelBuilder.Entity("LoopGame.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("ApplicationRole", "public");
                });

            modelBuilder.Entity("LoopGame.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("ApplicationUser", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationRoleClaim", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUserClaim", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUserLogin", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationUserRole", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("ApplicationUserToken", "public");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Assessment.AssessmentEvent", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("AssessmentEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Assessment.ConceptMasterySnapshot", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("MasterySnapshots")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Narrative.Shift", "Shift")
                        .WithMany("MasterySnapshots")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Audit.AiGenerationLog", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("AiGenerationLogs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.SideTask.SideTaskTemplate", "Template")
                        .WithMany("AiGenerationLogs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Code.PracticeAttempt", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("PracticeAttempts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Code.PracticeTask", "Task")
                        .WithMany("Attempts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Code.PracticeTask", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Narrative.Shift", "Shift")
                        .WithMany("PracticeTasks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Code.TestCase", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Code.PracticeTask", "Task")
                        .WithMany("TestCases")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LoopGame.Domain.Entities.SideTask.SideTaskTemplate", "Template")
                        .WithMany("TestCases")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Task");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.PlayerEconomy", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("Economy")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.PlayerInventory", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Economy.ShopItem", "Item")
                        .WithMany("PlayerInventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.SahmSubscription", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("SahmSubscriptions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.Transaction", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("Transactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.Choice", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Narrative.StoryBeat", "Beat")
                        .WithMany("Choices")
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Narrative.Consequence", "Consequence")
                        .WithMany()
                        .HasForeignKey("ConsequenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Beat");

                    b.Navigation("Consequence");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.Consequence", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Narrative.StoryBeat", "Beat")
                        .WithOne("Consequence")
                        .HasForeignKey("LoopGame.Domain.Entities.Narrative.Consequence", "BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.StoryBeat", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Narrative.Shift", "Shift")
                        .WithMany("StoryBeats")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.ConsequenceQueue", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Narrative.Consequence", "Consequence")
                        .WithMany("ConsequenceQueues")
                        .HasForeignKey("ConsequenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("ConsequenceQueues")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consequence");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.Player", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Narrative.Shift", "CurrentShift")
                        .WithMany()
                        .HasForeignKey("CurrentShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("Player")
                        .HasForeignKey("LoopGame.Domain.Entities.Player.Player", "PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentShift");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.PlayerChoice", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Narrative.StoryBeat", "Beat")
                        .WithMany()
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Narrative.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("PlayerChoices")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");

                    b.Navigation("Choice");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.PlayerSave", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("PlayerSaves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.PlayerShiftProgress", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("ShiftProgresses")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.Narrative.Shift", "Shift")
                        .WithMany("ShiftProgresses")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.PlayerSideTask", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Audit.AiGenerationLog", "AiLog")
                        .WithMany("PlayerSideTasks")
                        .HasForeignKey("AiLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany("SideTasks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.SideTask.SideTaskTemplate", "Template")
                        .WithMany("PlayerSideTasks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiLog");

                    b.Navigation("Player");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.SideTaskHint", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.SideTask.PlayerSideTask", "SideTask")
                        .WithMany("Hints")
                        .HasForeignKey("SideTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SideTask");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.SideTaskSubmission", b =>
                {
                    b.HasOne("LoopGame.Domain.Entities.Player.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoopGame.Domain.Entities.SideTask.PlayerSideTask", "SideTask")
                        .WithMany("Submissions")
                        .HasForeignKey("SideTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("SideTask");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LoopGame.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Audit.AiGenerationLog", b =>
                {
                    b.Navigation("PlayerSideTasks");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Code.PracticeTask", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Economy.ShopItem", b =>
                {
                    b.Navigation("PlayerInventories");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.Consequence", b =>
                {
                    b.Navigation("ConsequenceQueues");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.Shift", b =>
                {
                    b.Navigation("MasterySnapshots");

                    b.Navigation("PracticeTasks");

                    b.Navigation("ShiftProgresses");

                    b.Navigation("StoryBeats");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Narrative.StoryBeat", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("Consequence");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.Player.Player", b =>
                {
                    b.Navigation("AiGenerationLogs");

                    b.Navigation("AssessmentEvents");

                    b.Navigation("ConsequenceQueues");

                    b.Navigation("Economy");

                    b.Navigation("Inventory");

                    b.Navigation("MasterySnapshots");

                    b.Navigation("PlayerChoices");

                    b.Navigation("PlayerSaves");

                    b.Navigation("PracticeAttempts");

                    b.Navigation("SahmSubscriptions");

                    b.Navigation("ShiftProgresses");

                    b.Navigation("SideTasks");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.PlayerSideTask", b =>
                {
                    b.Navigation("Hints");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("LoopGame.Domain.Entities.SideTask.SideTaskTemplate", b =>
                {
                    b.Navigation("AiGenerationLogs");

                    b.Navigation("PlayerSideTasks");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("LoopGame.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Player");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
