using LoopGame.Domain.Entities.Narrative;
using LoopGame.Domain.Entities.Assessment;
using LoopGame.Application.Dtos;
using LoopGame.Application.Dtos.NarrativeDtos;
using LoopGame.Domain.Enums;

namespace LoopGame.Application.Mapping;

public class MapsterConfiguration : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        config.NewConfig<PracticeTask, PracticeDto>()
            .Map(dest => dest.ShiftNumber, src => src.Shift != null ? src.Shift.ShiftNumber : 0)
            .Map(dest => dest.TestCases, src => src.TestCases);

        config.NewConfig<PracticeDto, PracticeTask>()
            .Map(dest => dest.TestCases, src => src.TestCases);

        config.NewConfig<TestCase, TestCaseDto>();
        config.NewConfig<TestCaseDto, TestCase>();

        // Choice Mappings
        config.NewConfig<Choice, ChoiceDto>();
        config.NewConfig<ChoiceDto, Choice>();

        config.NewConfig<CreateChoiceDto, Choice>();
        config.NewConfig<Choice, CreateChoiceDto>();

        config.NewConfig<UpdateChoiceDto, Choice>()
            .IgnoreNullValues(true);

        // ── Narrative Mappings ────────────────────────────────────────────────

        config.NewConfig<Shift, ShiftDto>();

        // CreateShiftDto → Shift
        // Title trimming is done in the service before .Adapt() is called.
        config.NewConfig<CreateShiftDto, Shift>()
            .Ignore(dest => dest.ShiftId)         // auto-generated by DB
            .Ignore(dest => dest.CreatedAt)       // set by DB default / service
            .Ignore(dest => dest.StoryBeats)
            .Ignore(dest => dest.PracticeTasks)
            .Ignore(dest => dest.ShiftProgresses)
            .Ignore(dest => dest.MasterySnapshots);

        // Shift → ShiftDetailDto
        // NarrativeBeats and ConsequenceBeats are derived from the same StoryBeats collection
        // using filtering + ordering — Mapster handles this via the custom Map() expressions.
        config.NewConfig<Shift, ShiftDetailDto>()
            .Map(dest => dest.NarrativeBeats,
                src => src.StoryBeats
                    .Where(b => b.BeatType == BeatType.Narrative)
                    .OrderBy(b => b.SequenceOrder)
                    .Adapt<List<BeatDto>>())
            .Map(dest => dest.ConsequenceBeats,
                src => src.StoryBeats
                    .Where(b => b.BeatType == BeatType.Consequence)
                    .Adapt<List<BeatDto>>());

        config.NewConfig<StoryBeat, BeatDto>();

        config.NewConfig<CreateStoryBeatDto, StoryBeat>()
            .IgnoreNullValues(true);

        config.NewConfig<UpdateStoryBeatDto, StoryBeat>()
            .IgnoreNullValues(true)
            .Ignore(dest => dest.BeatKey)   // BeatKey is immutable after creation
            .Ignore(dest => dest.ShiftId);  // ShiftId handled explicitly in service

        // ── Assessment Mappings ────────────────────────────────────────────────
        config.NewConfig<AssessmentEventDto, AssessmentEvent>()
            .Map(dest => dest.Payload, src => src.PayloadJson)
            .Map(dest => dest.RecordedAt, src => src.RecordedAt.HasValue ? src.RecordedAt.Value : DateTime.UtcNow);

        config.NewConfig<AssessmentEvent, AssessmentEventDto>()
            .Map(dest => dest.PayloadJson, src => src.Payload);

        config.NewConfig<ConceptMasterySnapshot, ConceptMasterySnapshotDto>();
    }
}
